-- MySQL Script generated by MySQL Workbench
-- Sat Jul 31 10:42:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diploma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diploma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diploma` DEFAULT CHARACTER SET utf8 ;
USE `diploma` ;

-- -----------------------------------------------------
-- Table `diploma`.`specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diploma`.`specialization` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diploma`.`doctor` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `birth_date` VARCHAR(45) NOT NULL,
  `specialization_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doctor_specialization_idx` (`specialization_id` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_specialization`
    FOREIGN KEY (`specialization_id`)
    REFERENCES `diploma`.`specialization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	q	';


-- -----------------------------------------------------
-- Table `diploma`.`cabinet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diploma`.`cabinet` (
  `id` INT NOT NULL,
  `number` INT NOT NULL,
  `equipment` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`ad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diploma`.`ad` (
  `id` INT NOT NULL,
  `short` VARCHAR(45) NOT NULL,
  `full` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diploma`.`news` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `next` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`tab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diploma`.`tab` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diploma`.`page` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `text` TEXT(10000) NOT NULL,
  `tab_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_page_tab1_idx` (`tab_id` ASC) VISIBLE,
  CONSTRAINT `fk_page_tab1`
    FOREIGN KEY (`tab_id`)
    REFERENCES `diploma`.`tab` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diploma`.`shift` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `start_time` INT NOT NULL,
  `end_time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`timetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diploma`.`timetable` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `doctor_id` INT NOT NULL,
  `cabinet_id` INT NOT NULL,
  `shift_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_timetable_doctor1_idx` (`doctor_id` ASC) VISIBLE,
  INDEX `fk_timetable_cabinet1_idx` (`cabinet_id` ASC) VISIBLE,
  INDEX `fk_timetable_shift1_idx` (`shift_id` ASC) VISIBLE,
  CONSTRAINT `fk_timetable_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `diploma`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timetable_cabinet1`
    FOREIGN KEY (`cabinet_id`)
    REFERENCES `diploma`.`cabinet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timetable_shift1`
    FOREIGN KEY (`shift_id`)
    REFERENCES `diploma`.`shift` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diploma`.`patient` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `card_code` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`voucher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diploma`.`voucher` (
  `id` INT NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `nember` VARCHAR(45) NOT NULL,
  `patient_id` INT NOT NULL,
  `timetable_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_voucher_patient1_idx` (`patient_id` ASC) VISIBLE,
  INDEX `fk_voucher_timetable1_idx` (`timetable_id` ASC) VISIBLE,
  CONSTRAINT `fk_voucher_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `diploma`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voucher_timetable1`
    FOREIGN KEY (`timetable_id`)
    REFERENCES `diploma`.`timetable` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diploma`.`card_extract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diploma`.`card_extract` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `is_done` VARCHAR(45) NOT NULL,
  `target` VARCHAR(45) NOT NULL,
  `card_extractcol` VARCHAR(45) NOT NULL,
  `patient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_card_extract_patient1_idx` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_card_extract_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `diploma`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
